name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: yarn
      - name: Run lint
        run: |
          yarn lint
          yarn format
      - name: Run tests
        if: github.ref != 'refs/heads/main'
        run: yarn test
      - name: Run tests and generate coverage badge
        run: yarn run test:badges
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: |
            coverage/badge-functions.svg
            coverage/badge-lines.svg
